name: movie-theatre

services:
  movies-db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - movies-database:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms150m -Xmx150m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9200
    restart: always

  etl:
    build: ./etl
    env_file:
      - .env
    depends_on:
      - movies-db
      - elasticsearch
      - redis

  redis:
    image: redis
    container_name: redis
    env_file:
      - .env
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - rds-data:/data
      - redis.conf:/usr/local/etc/redis/redis.conf

  api-service:
    build: ./fastapi-solution
    ports:
      - "8000:8000"
    depends_on:
      - movies-db
      - elasticsearch

volumes:
  movies-database:
  es-data:
  etl-data:
  rds-data:
  redis.conf:


